import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:shamo/model/model.dart';
import 'package:shamo/pages/pages.dart';
import 'package:shamo/provider/providers.dart';
import 'package:shamo/theme.dart';
import 'package:intl/intl.dart';

part 'text_field_custom.dart';
part 'popular_products.dart';
part 'product_tile.dart';
part 'custom_page.dart';
part 'chat_tile.dart';
part 'header.dart';
part 'chat_buble.dart';
part 'wishlist_card.dart';
part 'cart_card.dart';
part 'checkout_card.dart';
part 'loading_button.dart';
